import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { hexToRgb, ramp, rgbToHex, SHADES } from '../../src/lib/scene/color.ts';
import { MATERIALS, type Material } from '../../src/lib/scene/materials.ts';
import { ART_DIR, KEY_PALETTE_GPL, KEY_PALETTE_JSON, type KeyPaletteFile } from './lib/paths.ts';

// Frozen: these values are baked into every sheet, so later palette tuning must not change them.
const KEY_BASE: Record<Material, string> = {
	wall: '#3d4268',
	floor: '#2c2f4d',
	desk: '#4d4669',
	chair: '#2f2a47',
	rug: '#5a4a7d',
	plant: '#3f7d76',
	pot: '#6f5b8f',
	frame: '#5a6090',
	poster: '#4f5584',
	curtain: '#4a3d78',
	skin: '#d6a68c',
	hair: '#141226',
	glasses: '#e3a0b2',
	sweater: '#6b7fd4',
	laptop: '#9da6c8',
	tabby: '#8e8ba3',
	catWhite: '#e8e5f3',
	nose: '#e08aa2',
	eye: '#8fd8b2',
	coffee: '#5a3a3c',
	milk: '#c9a390',
	straw: '#e070a4',
	lamp: '#f0c26e',
	lampGlow: '#ffd383',
	cushion: '#5b4a8c',
	screen: '#8fe4ff',
	book0: '#7b5dc6',
	book1: '#3c909b',
	book2: '#c65d8c',
	sticker0: '#ff70a9',
	sticker1: '#5ae0d0',
	sticker2: '#ffd36e',
	sticker3: '#9c8cff',
	building: '#262a52',
	hoodie: '#2b2a3a',
	jeans: '#3b4468',
	cork: '#b98a5c',
	wood: '#7c5c4a',
	paper: '#ece6d8',
	radio: '#4f8f93'
};
const SHADOW_HUE = 245;
const LIGHT_HUE = 190;

const FIXED: Record<string, string> = {
	white: '#ffffff'
};

function build(): KeyPaletteFile {
	const used = new Set<string>(Object.values(FIXED));
	const unique = (hex: string): string => {
		const [r, g, b] = hexToRgb(hex);
		for (let step = 0; ; step++) {
			const d = (step >> 1) * (step & 1 ? -1 : 1);
			const candidate = rgbToHex(step < 20 ? [r, g, b + d] : [r, g + d - 10, b]);
			if (!used.has(candidate)) {
				used.add(candidate);
				return candidate;
			}
		}
	};
	const keys = {} as KeyPaletteFile['keys'];
	for (const m of MATERIALS) {
		const r = ramp(KEY_BASE[m], SHADOW_HUE, LIGHT_HUE);
		keys[m] = SHADES.map((s) => unique(r[s])) as KeyPaletteFile['keys'][Material];
	}
	return {
		note: 'Generated by scripts/art/key-palette.ts and frozen. Index 0 is transparent; then each material in order with shades d2, d, b, l; then the fixed colours.',
		materials: [...MATERIALS],
		shades: [...SHADES],
		keys,
		fixed: FIXED
	};
}

function gpl(file: KeyPaletteFile): string {
	const lines = ['GIMP Palette', 'Name: joelleortiz.me key palette', 'Columns: 4', '#'];
	const row = (hex: string, name: string) => {
		const [r, g, b] = hexToRgb(hex);
		lines.push(
			`${String(r).padStart(3)} ${String(g).padStart(3)} ${String(b).padStart(3)}\t${name}`
		);
	};
	row('#000000', 'transparent (index 0)');
	for (const m of file.materials) file.shades.forEach((s, i) => row(file.keys[m][i], `${m} ${s}`));
	for (const [name, hex] of Object.entries(file.fixed)) row(hex, `${name} (fixed)`);
	return lines.join('\n') + '\n';
}

const force = process.argv.includes('--force');
if (existsSync(KEY_PALETTE_JSON) && !force) {
	console.log(`Key palette already frozen at ${KEY_PALETTE_JSON} (use --force to regenerate).`);
} else {
	const file = build();
	mkdirSync(dirname(KEY_PALETTE_JSON), { recursive: true });
	writeFileSync(KEY_PALETTE_JSON, JSON.stringify(file, null, '\t') + '\n');
	writeFileSync(KEY_PALETTE_GPL, gpl(file));
	console.log(`Wrote ${KEY_PALETTE_JSON} and ${KEY_PALETTE_GPL} in ${ART_DIR}.`);
}
